import { ArrowUpRight, CircleDot } from "lucide-react";
import type { Run } from "../types";
import { PageShell } from "../components/page-shell";

export function HistoryScreen({ runs, onOpen }: { runs: Run[]; onOpen(run: Run): void }) {
  return <PageShell eyebrow="RUN LEDGER" title="Application history" description="Durable run metadata from the backend. Open a run to inspect its replay, browser state, and artifacts."><div className="overflow-hidden rounded-xl border border-stone-200 bg-white dark:border-zinc-800 dark:bg-zinc-900"><table className="w-full text-left text-xs"><thead className="bg-stone-50 font-mono text-[9px] tracking-[.12em] text-stone-400 uppercase dark:bg-zinc-950 dark:text-zinc-500"><tr><th className="px-4 py-3">Application</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Phase</th><th className="px-4 py-3">Outcome</th><th className="px-4 py-3">Started</th><th className="w-12"/></tr></thead><tbody>{runs.map((run) => <tr className="border-t border-stone-100 hover:bg-violet-50/50 dark:border-zinc-800 dark:hover:bg-violet-950/20" key={run.id}><td className="px-4 py-3"><b className="block text-sm text-stone-900 dark:text-zinc-100">{run.company || hostname(run.job_url)}</b><span className="mt-0.5 block text-stone-400">{run.role || run.job_url}</span></td><td className="px-4 py-3"><span className="inline-flex items-center gap-1.5"><CircleDot size={12} className={run.status === "waiting_human" ? "text-amber-500" : run.status === "terminal" ? "text-stone-400" : "text-cyan-500"}/>{run.status.replaceAll("_", " ")}</span></td><td className="px-4 py-3 capitalize">{run.phase.replaceAll("_", " ")}</td><td className="px-4 py-3 capitalize">{run.outcome?.replaceAll("_", " ") || "—"}</td><td className="px-4 py-3 text-stone-500">{formatDate(run.started_at || run.created_at)}</td><td><button className="grid size-8 place-items-center rounded text-stone-400 hover:bg-violet-100 hover:text-violet-700 dark:hover:bg-violet-950" onClick={() => onOpen(run)} title="Open run"><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table>{runs.length === 0 && <p className="p-8 text-center text-sm text-stone-500">No applications have been recorded yet.</p>}</div></PageShell>;
}

function hostname(url: string): string { try { return new URL(url).hostname.replace("www.", ""); } catch { return "Application"; } }
function formatDate(value: string): string { return new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }); }

