import { AnimatePresence, motion } from "framer-motion";
import { Bot, CircleAlert, LoaderCircle, Send, ShieldAlert, Wrench } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ActivityEvent, HumanRequest, Run } from "../types";
import { ToolActivity } from "./ai/tool-activity";

interface Props { run: Run; events: ActivityEvent[]; pendingRequest?: HumanRequest; onAnswer(answer: string): void; }

export function AgentConversation({ run, events, pendingRequest, onAnswer }: Props) {
  const viewport = useRef<HTMLDivElement>(null);
  const activity = useMemo(() => curateEvents(events), [events]);
  useEffect(() => { viewport.current?.scrollTo({ top: viewport.current.scrollHeight, behavior: "smooth" }); }, [activity.length]);
  return <section className="grid h-full min-h-0 grid-rows-[auto_auto_minmax(0,1fr)_auto] overflow-hidden bg-white">
    <header className="flex items-center justify-between border-b border-stone-200 px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-violet-600 text-violet-50 shadow-lg shadow-violet-200"><Bot size={18}/></span><div><span className="font-mono text-[10px] tracking-[.14em] text-stone-500">LIVE RUN NARRATIVE</span><h2 className="mt-0.5 text-base font-semibold text-stone-950">What the agent is doing</h2></div></div><div className="hidden font-mono text-[10px] text-stone-500 sm:block"><span className="mr-1.5 inline-block size-1.5 rounded-full bg-cyan-500 shadow-sm shadow-cyan-300"/>Streaming activity</div></header>
    <div className="flex items-start gap-3 border-b border-stone-200 bg-stone-50 px-5 py-4"><span className={`mt-3 size-2 shrink-0 rounded-full ${nowTone(run.status)}`}/><div><span className="font-mono text-[10px] tracking-[.14em] text-stone-500">HAPPENING NOW</span><p className="mt-1 text-sm leading-relaxed text-stone-800">{nowDescription(run)}</p></div><span className="ml-auto mt-1 hidden shrink-0 rounded-full border border-stone-300 px-2 py-1 font-mono text-[9px] text-stone-500 sm:inline">{run.status === "human_control" ? "You control" : "Agent controls"}</span></div>
    <div className="min-h-0 overflow-y-auto scroll-smooth" ref={viewport} aria-live="polite"><div className="mx-auto flex max-w-2xl flex-col gap-4 px-5 py-5"><div className="ml-10 font-mono text-[10px] tracking-[.1em] text-stone-400 uppercase">Verified activity</div><AnimatePresence initial={false}>{activity.map((event) => <ConversationMessage event={event} key={event.database_id}/>)}</AnimatePresence>{pendingRequest ? <HumanNeeded request={pendingRequest}/> : <ListeningState run={run}/>}</div></div>
    <ChatComposer pendingRequest={pendingRequest} onAnswer={onAnswer}/>
  </section>;
}

function ConversationMessage({ event }: { event: ActivityEvent }) {
  const tool = event.type.includes("tool"); const Icon = event.level === "error" ? CircleAlert : tool ? Wrench : Bot;
  return <motion.article className="grid grid-cols-[30px_minmax(0,1fr)] gap-2.5" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -4 }} transition={{ duration: 0.22 }}><span className={`grid size-[29px] place-items-center rounded-lg ${event.level === "error" ? "bg-rose-100 text-rose-700" : "bg-violet-100 text-violet-700"}`}><Icon size={15}/></span><div className={`min-w-0 rounded-r-xl rounded-bl-xl border p-3 ${event.level === "error" ? "border-rose-200 bg-rose-50" : "border-stone-200 bg-stone-50"}`}><div className="flex items-baseline gap-2"><b className="text-xs text-stone-950 capitalize">{speaker(event)}</b><time className="font-mono text-[10px] text-stone-400">{formatTime(event.occurred_at)}</time></div><p className="mt-2 text-sm leading-relaxed text-stone-700">{describe(event)}</p>{tool && <ToolActivity event={event}/>}</div></motion.article>;
}

function HumanNeeded({ request }: { request: HumanRequest }) { return <article className="grid grid-cols-[30px_minmax(0,1fr)] gap-2.5"><span className="grid size-[29px] place-items-center rounded-lg bg-amber-200 text-amber-950"><ShieldAlert size={15}/></span><div className="min-w-0 rounded-r-xl rounded-bl-xl border border-amber-300/50 bg-amber-950/40 p-3"><div className="flex items-baseline gap-2"><b className="text-xs text-amber-100">Your input is needed</b><span className="font-mono text-[10px] text-amber-200/70">agent paused safely</span></div><p className="mt-2 text-sm leading-relaxed text-amber-50">{request.question}</p><small className="mt-2 block text-xs text-amber-200">Reply in the composer below to continue.</small></div></article>; }
function ChatComposer({ pendingRequest, onAnswer }: { pendingRequest?: HumanRequest; onAnswer(answer: string): void }) { const [value, setValue] = useState(""); const canSend = Boolean(pendingRequest && value.trim()); return <form className="border-t border-stone-200 bg-white p-4" onSubmit={(event) => { event.preventDefault(); if (!canSend) return; onAnswer(value.trim()); setValue(""); }}><div className="mx-auto flex max-w-2xl items-center gap-2 rounded-xl border border-stone-300 bg-stone-50 p-2 focus-within:border-violet-400"><textarea className="min-h-10 flex-1 resize-none bg-transparent px-2 py-1 text-sm text-stone-950 outline-none placeholder:text-stone-400 disabled:cursor-not-allowed" value={value} onChange={(event) => setValue(event.target.value)} placeholder={pendingRequest ? "Reply to the agent…" : "The agent will open this composer when it needs your input."} disabled={!pendingRequest} rows={1}/><button className="grid size-9 place-items-center rounded-lg bg-violet-600 text-violet-50 transition hover:bg-violet-500 disabled:cursor-not-allowed disabled:bg-stone-200 disabled:text-stone-400" disabled={!canSend} type="submit" aria-label="Send reply"><Send size={16}/></button></div><p className="mx-auto mt-2 max-w-2xl px-2 text-[11px] text-stone-400">{pendingRequest ? "Your response will be sent to the active human checkpoint." : "The agent is working autonomously. You will only be asked for information it cannot safely infer."}</p></form>; }
function ListeningState({ run }: { run: Run }) { if (run.status === "terminal") return <div className="ml-10 border-l-2 border-zinc-700 pl-3 text-xs text-zinc-500">This run has finished. Its recorded outcome is in the context pane.</div>; return <div className="ml-10 flex items-center gap-2 text-xs text-zinc-500"><LoaderCircle className="animate-spin text-cyan-300" size={14}/>{run.status === "waiting_human" ? "Waiting for your decision" : "Listening for the next verified update"}</div>; }

function nowDescription(run: Run): string { if (run.status === "waiting_human") return "The agent has paused safely and needs your response before continuing."; if (run.status === "human_control") return "You have browser control. The agent is paused until you return it."; if (run.status === "terminal") return run.summary || "This run has reached its recorded outcome."; return `${agentStartedDescription(canonicalAgent(run.current_agent))} Phase: ${run.phase.replaceAll("_", " ")}.`; }
function nowTone(status: Run["status"]): string { if (status === "waiting_human") return "bg-amber-300 shadow-sm shadow-amber-300"; if (status === "human_control") return "bg-violet-300 shadow-sm shadow-violet-300"; if (status === "terminal") return "bg-zinc-600"; return "bg-cyan-300 shadow-sm shadow-cyan-300"; }
function speaker(event: ActivityEvent): string { const candidate = event.source.agent || event.source.name || event.source.component; if (candidate) return candidate.replaceAll("_", " "); if (event.type.startsWith("browser.")) return "Browser workspace"; return "Application agent"; }
function describe(event: ActivityEvent): string { const payload = event.payload; for (const key of ["message", "summary", "detail", "description", "action", "reason"]) { const value = payload[key]; if (typeof value === "string" && value.trim()) return value; } const descriptions: Record<string, string> = { "run.queued": "The application has been placed in the execution queue.", "run.started": "The run has started and the persistent workspace is being prepared.", "run.terminal": "The run reached a terminal state. Review the outcome in the context pane.", "agent.started": agentStartedDescription(event.source.agent), "agent.completed": "A specialist completed its assigned step and returned evidence to the orchestrator.", "tool.started": "Inspecting the current browser evidence before taking the next action.", "tool.completed": "The browser action completed and its evidence was recorded.", "human.requested": "The agent needs an explicit human decision before it can continue.", "human.resolved": "Your response was recorded and the agent can continue safely.", "browser.control_taken": "Browser control is now with you; agent mutations are paused.", "browser.control_returned": "Browser control was returned to the agent." }; return descriptions[event.type] || `Recorded ${event.type.replaceAll(".", " ").replaceAll("_", " ")}.`; }
function curateEvents(events: ActivityEvent[]): ActivityEvent[] { const retained: ActivityEvent[] = []; let lastAgent: string | undefined; for (const event of [...events].sort((left, right) => left.sequence - right.sequence)) { if (event.level === "error" || event.type.startsWith("run.") || event.type.startsWith("human.") || event.type.startsWith("browser.") || event.type === "model.selected") { retained.push(event); continue; } if (event.type === "agent.started") { const agent = canonicalAgent(event.source.agent); if (agent && agent !== lastAgent) retained.push(event); lastAgent = agent; continue; } if (event.type === "agent.completed") { retained.push(event); continue; } if (event.type.startsWith("tool.") && hasVisibleToolDetail(event)) retained.push(event); } return retained.slice(-28); }
function canonicalAgent(value?: string | null): string | undefined { return value?.split(":", 1)[0]; }
function hasVisibleToolDetail(event: ActivityEvent): boolean { return ["message", "summary", "detail", "description", "action", "name", "error"].some((key) => { const value = event.payload[key]; return typeof value === "string" && value.trim().length > 0; }); }
function agentStartedDescription(agent?: string): string { const descriptions: Record<string, string> = { authenticate_default_account: "Checking the saved authenticated browser session.", lifecycle: "Preparing the persistent browser workspace.", orchestrator: "Coordinating the next verified application step.", values: "Loading the application profile values." }; const canonical = canonicalAgent(agent); return canonical ? descriptions[canonical] || `The ${canonical.replaceAll("_", " ")} specialist started its step.` : "A specialist has started its assigned application step."; }
function formatTime(value: string): string { return new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); }
