import { Expand, Eye, Focus, LockKeyhole, MonitorUp, MousePointer2, RefreshCw, ShieldCheck } from "lucide-react";
import type { LiveView, Run } from "../types";
import { GlowFrame } from "./cult/glow-frame";
import { NoVncCanvas } from "./no-vnc-canvas";

interface Props { run: Run; live?: LiveView; onFocus(): void; onControl(): void; onReturn(): void; }

export function BrowserPanel({ run, live, onFocus, onControl, onReturn }: Props) {
  const human = live?.control_mode === "human_control";
  return <section className={`relative grid min-h-0 flex-1 grid-rows-[auto_1fr_auto_auto] overflow-hidden rounded-xl border bg-white dark:bg-zinc-900 ${human ? "border-amber-300" : "border-stone-200 dark:border-zinc-800"}`}>
    <div className="flex items-center justify-between border-b border-stone-200 px-4 py-3"><div className="flex items-center gap-2"><span className="size-1.5 rounded-full bg-cyan-500 shadow-sm shadow-cyan-300"/><div><b className="block text-sm text-stone-950">Shared Camoufox workspace</b><small className="mt-1 block font-mono text-[10px] text-stone-500">{live?.available ? "Live surface connected" : "Waiting for browser workspace"}</small></div></div><div className="flex gap-1"><IconButton title="Focus run" onClick={onFocus}><Focus size={15}/></IconButton><IconButton title="Reconnect"><RefreshCw size={15}/></IconButton><IconButton title="Fullscreen"><Expand size={15}/></IconButton></div></div>
    {human && <div className="flex items-center gap-2 bg-amber-200 px-4 py-2.5 text-xs text-amber-950"><MousePointer2 size={15}/><b>You control the browser</b><span className="opacity-75">Agent mutations are paused.</span></div>}
    <GlowFrame><div className={`relative grid h-full min-h-0 place-items-center overflow-hidden ${live?.websocket_url ? "bg-slate-950" : "bg-stone-50"}`}>{live?.websocket_url ? <NoVncCanvas websocketUrl={live.websocket_url} viewOnly={!human}/> : <div className="max-w-xs p-6 text-center"><div className="mx-auto mb-5 grid size-16 place-items-center rounded-2xl border border-stone-200 bg-white text-violet-600 shadow-sm shadow-stone-200"><MonitorUp size={28}/></div><h2 className="text-base font-semibold text-stone-900">{live?.available ? "Browser view ready" : "Browser will appear here"}</h2><p className="my-2 text-xs leading-relaxed text-stone-500">{live?.available ? "Connect to the focused application through the local noVNC bridge." : "Start an application and its persistent browser will take over this workspace."}</p><div className="flex justify-center gap-1.5"><Meta><Eye size={13}/>{run.browser_tab_state}</Meta><Meta><ShieldCheck size={13}/>{human ? "human control" : "agent control"}</Meta></div></div>}</div></GlowFrame>
    <div className="flex items-center justify-between border-t border-stone-200 px-4 py-3 text-xs text-stone-500"><span>Focused <b className="font-medium text-stone-800">{run.company || "application"}</b></span>{human ? <button className="rounded-md bg-violet-600 px-3 py-2 text-xs font-bold text-violet-50" onClick={onReturn}>Return to agent</button> : <button className="flex items-center gap-1.5 rounded-md border border-violet-500 bg-violet-600 px-3 py-2 text-xs text-violet-50" onClick={onControl}><MousePointer2 size={14}/> Take control</button>}</div>
    {!human && <div className="flex items-center justify-center gap-1.5 border-t border-stone-200 bg-stone-50 py-2 font-mono text-[10px] text-stone-500"><LockKeyhole size={13} /> View only until you take control</div>}
  </section>;
}

function IconButton({ children, title, onClick }: React.PropsWithChildren<{ title: string; onClick?: () => void }>) { return <button className="grid size-8 place-items-center rounded-md border border-stone-200 bg-stone-50 text-stone-600 hover:bg-stone-100" title={title} onClick={onClick}>{children}</button>; }
function Meta({ children }: React.PropsWithChildren) { return <span className="flex items-center gap-1 rounded-md border border-stone-200 bg-white px-2 py-1.5 font-mono text-[10px] uppercase text-stone-500">{children}</span>; }
