import { ArrowRight, BriefcaseBusiness, Link, Sparkles } from "lucide-react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "./ui/button";

const schema = z.object({ url: z.url("Enter a complete job URL."), task: z.string().max(10_000).optional() });
type Form = z.infer<typeof schema>;

export function StartRun({ onSubmit }: { onSubmit(url: string, task: string): void }) {
  const form = useForm<Form>({ resolver: zodResolver(schema), defaultValues: { url: "", task: "" } });
  return <main className="mx-auto grid min-h-[calc(100vh-118px)] max-w-6xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.1fr_.9fr]"><div><div className="flex items-center gap-2 font-mono text-[10px] tracking-[.14em] text-emerald-300"><Sparkles size={15}/> LOCAL AUTONOMOUS APPLY</div><h1 className="my-5 max-w-xl text-5xl font-semibold leading-[.95] tracking-tighter text-slate-100 sm:text-6xl">Send a capable agent into the application.</h1><p className="max-w-lg text-[17px] leading-relaxed text-slate-400">One persistent browser. Evidence-first actions. You remain the approving authority.</p><div className="mt-8 flex flex-wrap gap-3"><span className="flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2.5 text-xs text-slate-200"><BriefcaseBusiness size={16} className="text-emerald-300"/> Agent-led execution</span><span className="flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2.5 text-xs text-slate-200"><Link size={16} className="text-emerald-300"/> Shared authenticated browser</span></div></div><form className="rounded-2xl border border-slate-700 bg-slate-900 p-7 shadow-2xl shadow-black/25" onSubmit={form.handleSubmit(({ url, task }) => onSubmit(url, task ?? ""))}><div className="flex justify-between font-mono text-[11px] tracking-[.1em] text-violet-200"><span>NEW APPLICATION</span><i className="not-italic text-slate-500">01</i></div><label className="mt-6 block text-xs text-slate-200">Job URL<input autoFocus className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-3 text-slate-100 outline-none placeholder:text-slate-500 focus:border-violet-400" placeholder="https://company.com/careers/job" {...form.register("url")}/></label><label className="mt-5 block text-xs text-slate-200">Mission override <em className="not-italic text-slate-500">optional</em><textarea className="mt-2 w-full resize-y rounded-lg border border-slate-700 bg-slate-950 px-3 py-3 text-slate-100 outline-none placeholder:text-slate-500 focus:border-violet-400" placeholder="e.g. Prioritize platform engineering roles and surface non-standard questions." rows={4} {...form.register("task")}/></label>{form.formState.errors.url && <p className="mt-2 text-xs text-rose-300">{form.formState.errors.url.message}</p>}<Button className="mt-6 flex w-full justify-between px-4 py-3" type="submit"><span>Launch application</span><ArrowRight size={18}/></Button><small className="mt-4 block text-center text-[10px] text-slate-500">Final submission is always gated by your explicit approval.</small></form></main>;
}
